#!/bin/bash
. test/integration/helper

test_series_generates_specified_series_for_5_steps_of_1 () {
series "linear 2 1" "geometric 2 3" "fibonacci"  | assert_output "\
1.0 2.0 0
3.0 6.0 1
5.0 18.0 1
7.0 54.0 2
9.0 162.0 3
"
}

#
# -h
#

test_series_h_prints_help () {
series -h | grep -q "usage: series"
}

. ts
