#!/bin/bash
. test/integration/helper

test_series_step () {
series step 0:1 | assert_output "\
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
"
}

test_series_step_follow_offset_step_size_and_n_steps () {
series step 10:2.1:3 | assert_output "\
10.0
12.1
14.2
"
}

test_series_step_print_sprial_series_at_each_input_x () {
printf "%s\n" 0 1 2 5 2 | series-step 0:1 | assert_output "\
0.0
1.0
2.0
5.0
2.0
"
}

test_series_step_supports_multiple_dimensions () {
series -r 0 step 0:1:2 0:1:2 | assert_output "\
0 0
0 1
1 0
1 1
"
}

#
# -h
#

test_series_step_h_prints_help () {
series-step -h | grep -q "usage: series-step"
}

. ts
